name: 'Setup openpilot Environment (Native)'
description: 'Sets up the openpilot CI environment on a native runner with aggressive caching for apt and pip.'

inputs:
  is_retried:
    description: 'Input from retry wrapper, not used in this action.'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set system locale
      shell: bash
      run: |
        sudo sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
        sudo locale-gen

    - name: Cache and install apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: >-
          build-essential
          sudo tzdata locales ssh pulseaudio xvfb x11-xserver-utils
          gnome-screenshot python3-tk python3-dev
        version: 1.1

    - name: Set up Python and cache pip dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
      env:
        PYTHONUNBUFFERED: "1"
