name: 'Optimized Native Setup'

inputs:
  is_retried:
    description: 'Mock param for validation'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ inputs.is_retried == 'false' }}
      run: |
        echo "Use setup-with-retry instead."
        exit 1

    - shell: bash
      name: Disallow manual retries
      run: |
        if [ "${{ github.run_attempt }}" -gt 1 ]; then
          echo "No retries allowed"
          exit 1
        fi

    - shell: bash
      name: Install system packages
      run: |
        sudo apt update
        sudo apt install -y \
          git build-essential libusb-1.0-0-dev libcap-dev \
          libjpeg-dev libturbojpeg0-dev libopencv-dev \
          libprotobuf-dev protobuf-compiler libeigen3-dev \
          python3-dev python3-pip python3-venv

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          pip-cache-${{ runner.os }}

    - shell: bash
      name: Set up Python environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - shell: bash
      name: Generate diff.txt (process replay)
      run: |
        source venv/bin/activate
        python selfdrive/test/process_replay/process_replay.py --updatedb
        test -f selfdrive/test/process_replay/diff.txt || touch selfdrive/test/process_replay/diff.txt
