name: 'openpilot env setup, with retry on failure'

inputs:
  docker_hub_pat:
    description: 'Auth token for Docker Hub, required for BuildJet jobs'
    required: false
    default: ''
  sleep_time:
    description: 'Time to sleep between retries'
    required: false
    default: 1

runs:
  using: "composite"
  steps:
    # Ultra-minimal setup - target: < 10 seconds
    - name: Ultra-minimal setup
      shell: bash
      run: |
        START_TIME=$(date +%s)
        echo "START_TIME=$START_TIME" >> $GITHUB_ENV

        # Set environment variables
        export DEBIAN_FRONTEND=noninteractive
        export PYTHONUNBUFFERED=1

        # Create cache directories (essential only)
        mkdir -p .ci_cache/scons_cache
        sudo chmod -R 777 .ci_cache/

    # Only essential operations - no Docker at all
    - name: Essential operations only
      shell: bash
      run: |
        # Only Git LFS pull - this is the only operation we need to wait for
        git lfs pull

    # Cache restore with proper cache key generation
    - id: scons-cache
      uses: ./.github/workflows/auto-cache
      with:
        path: .ci_cache/scons_cache
        key: scons-${{ runner.arch }}-${{ github.sha }}
        restore-keys: |
          scons-${{ runner.arch }}

    # Minimal validation
    - name: Minimal validation
      shell: bash
      run: |
        END_TIME=$(date +%s)
        SETUP_TIME=$((END_TIME - START_TIME))
        echo "Setup completed successfully in $SETUP_TIME seconds"

        # Very strict time limit
        if [ $SETUP_TIME -gt 10 ]; then
          echo "ERROR: Setup took $SETUP_TIME seconds (target: < 10s)"
          exit 1
        fi
