name: 'openpilot env setup, with retry on failure'

inputs:
  docker_hub_pat:
    description: 'Auth token for Docker Hub, required for BuildJet jobs'
    required: false
    default: ''
  sleep_time:
    description: 'Time to sleep between retries'
    required: false
    default: 30

runs:
  using: "composite"
  steps:
       # 1) Checkout your repo
    - name: Checkout code
      uses: actions/checkout@v3


    # 2) Setup Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

       # 3) Cache pip wheels via your auto-cache action
    - name: Cache pip
      id: pip-cache
      uses: ./.github/workflows/auto-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('tools/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        save: 'true'


    # 4) Cache APT packages via your auto-cache action
    - name: Cache APT packages
      id: apt-cache
      uses: ./.github/workflows/auto-cache
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('apt_requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-
        save: 'true'

         # 5) Native install of system + Python deps
    - id: install
      name: Install system & Python dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        xargs -a apt_requirements.txt sudo apt-get install -qq -y
        pip install --no-cache-dir -r tools/requirements.txt

      # 6) Retry logic if the above failed
    - name: Retry install if it failed
      if: steps.install.outcome == 'failure'
      shell: bash
      run: |
        echo "Initial install failed, sleeping for ${{ inputs.sleep_time }}s…"
        sleep ${{ inputs.sleep_time }}
        sudo apt-get update -qq
        xargs -a apt_requirements.txt sudo apt-get install -qq -y
        pip install --no-cache-dir -r tools/requirements.txt
