name: Parallel CI Setup

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  parallel-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Make scripts executable
      run: |
        chmod +x ./prepare_parallel_cache.sh
        chmod +x ./setup_parallel_ci.sh

    - name: Prepare Parallel Cache
      run: |
        echo "🚀 Preparing parallel cache..."
        ./prepare_parallel_cache.sh

    - name: Run Parallel CI Setup
      run: |
        echo "⚡ Running parallel CI setup..."
        ./setup_parallel_ci.sh
        
    - name: Verify Setup
      run: |
        echo "🔍 Verifying parallel setup..."
        if [ -d ~/.venv ]; then
          echo "✅ Virtual environment created"
          source ~/.venv/bin/activate
          echo "✅ Environment activated"
          echo "Python: $(python --version)"
        else
          echo "❌ Virtual environment not found"
          exit 1
        fi
