name: Test GitHub Actions

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Simple test
      run: |
        echo "🚀 GitHub Actions is working!"
        echo "✅ Repository: ${{ github.repository }}"
        echo "📂 Branch: ${{ github.ref_name }}"
        echo "💻 Runner: ${{ runner.os }}"
        
    - name: Run quick test
      run: |
        echo "Running optimized test suite..."
        if [[ -f "test_cache_demo/test_simple.py" ]]; then
          echo "✅ Test files found"
          python3 --version
          pip3 install pytest
          python3 -m pytest test_cache_demo/ -v --tb=short || true
        else
          echo "⚠️  Test files not found, but workflow is running!"
        fi
        
    - name: Success notification
      run: |
        echo "🎉 Workflow completed successfully!"
        echo "⚡ This proves GitHub Actions are working on your repository!"
